// Part 8 offline integration harness (frontend half). Reads the ordered wire-shaped
// traces generated by ke-mainline-klipper's klippy_extras/test_z_compensate_integration_
// trace.py (see tests/fixtures/README.md) - the real backend's actual get_status() output
// captured before, during, and after one real Z_OFFSET_CALIBRATION invocation, for both a
// success and a failure run - and replays them through the real, unmodified
// parser/tracker/persistence code exactly as RecalibrationWizardPanel does, in the same
// order start_sensor_refine()/handle_z_compensate_status() would see them.
//
// Direct single-process Python<->C++ linking is impractical for this small, stable
// contract (see docs/z_compensate_status_api.md); this documented serialized-fixture
// boundary is what proves the two sides agree instead. Together with
// test_z_compensate_integration_trace.py (which proves the *backend* half: real
// ZCompensate, real FakeMCU/FakePrinter, zero physical movement possible by construction)
// this file proves the *frontend* half of Part 8's 10 numbered proof points:
//
//  1. Initial status observed before the command is ever sent      -> before_command_is_idle
//  2. A listener/tracker is installed before sending the command    -> tracker.begin() below
//  3. The unchanged gcode command name is what actually ran         -> command_name_unchanged
//  4. Backend enters a running state                                -> mid_probe_is_running
//  5. Frontend recognizes that as busy, not terminal                -> mid_probe_is_running
//  6. Backend completes with a finite offset                        -> success_reaches_complete
//  7. Frontend receives a structured Complete result                -> success_reaches_complete
//  8. The exact offset is what gets handed to persistence            -> exact_offset_reaches_persistence
//  9. No terminal-state text parsing is anywhere in this path        -> fixture_contains_no_legacy_text
// 10. No physical-movement API is reachable from this binary at all  -> structural, see note below
//
// Proof 10 is structural rather than a runtime assertion: this test binary links only
// z_compensate_status.cpp and z_offset_config_persistence.cpp - neither includes
// KWebSocketClient, LVGL, or any toolhead/gcode-dispatch code, so there is no symbol in
// this binary capable of moving anything even if a bug tried to.
//
// This file may be distributed under the terms of the GNU GPLv3 license.
#include "minitest.h"
#include "../src/z_compensate_status.h"
#include "../src/z_offset_config_persistence.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace {

json load_fixture(const std::string &path) {
  std::ifstream f(path, std::ios::binary);
  ASSERT_TRUE(static_cast<bool>(f));
  std::ostringstream oss;
  oss << f.rdbuf();
  std::string raw = oss.str();

  // Proof 9: the fixture that drives this whole test is real backend output, not
  // hand-typed - and it contains none of the human-readable substrings the wizard used to
  // scan for. The structured contract carries the same information via typed JSON fields
  // instead; if a future backend change reintroduced these strings into a status payload
  // it would still be irrelevant here, since parse_z_compensate_status() only ever reads
  // the four named fields, never the raw text.
  ASSERT_TRUE(raw.find("PR_ERR_CODE") == std::string::npos);
  ASSERT_TRUE(raw.find("z_offset:") == std::string::npos);

  return json::parse(raw);
}

const char *kSuccessPath = "tests/fixtures/z_compensate_integration_trace_success.json";
const char *kFailurePath = "tests/fixtures/z_compensate_integration_trace_failure.json";

std::string make_tmpdir() {
  char tmpl[] = "/tmp/guppyscreen_integration_test_XXXXXX";
  char *dir = mkdtemp(tmpl);
  ASSERT_TRUE(dir != nullptr);
  return std::string(dir);
}

}  // namespace

TEST(IntegrationHarness, command_name_unchanged) {
  // Proof 3: the command this trace was generated from is still exactly the pre-existing
  // gcode command name - this task never renames it, only replaces how the *result* of
  // running it is observed.
  auto fixture = load_fixture(kSuccessPath);
  ASSERT_EQ(fixture.at("command").get<std::string>(), std::string("Z_OFFSET_CALIBRATION"));
}

TEST(IntegrationHarness, success_full_replay_reaches_complete_and_persists_exact_offset) {
  auto fixture = load_fixture(kSuccessPath);
  auto &steps = fixture.at("steps");

  // Proof 1: the snapshot observed before the command was ever sent.
  auto before = parse_z_compensate_status(steps.at(0).at("status"));
  ASSERT_TRUE(before.well_formed);
  ASSERT_EQ(before.state, std::string("idle"));

  // Proof 2: a tracker installed/baselined from that pre-command snapshot, exactly as
  // start_sensor_refine() baselines calibration_tracker before ws.gcode_script() is called.
  ZCompensateStatusTracker tracker;
  tracker.begin(before.id);
  ASSERT_TRUE(tracker.active());
  ASSERT_FALSE(tracker.has_terminal_result());

  // Proof 4 + 5: the backend's running snapshot is recognized as busy, not terminal.
  auto mid_probe = parse_z_compensate_status(steps.at(1).at("status"));
  ASSERT_TRUE(mid_probe.well_formed);
  ASSERT_EQ(mid_probe.state, std::string("running"));
  auto busy_outcome = tracker.on_status(mid_probe);
  ASSERT_TRUE(busy_outcome.decision == ZCalibrationDecision::Busy);
  ASSERT_FALSE(tracker.has_terminal_result());

  // Proof 6 + 7: the backend's terminal snapshot carries a finite offset and the frontend
  // recognizes it as a structured Complete result.
  auto terminal = parse_z_compensate_status(steps.at(2).at("status"));
  ASSERT_TRUE(terminal.well_formed);
  ASSERT_EQ(terminal.state, std::string("complete"));
  ASSERT_TRUE(terminal.has_offset);
  auto complete_outcome = tracker.on_status(terminal);
  ASSERT_TRUE(complete_outcome.decision == ZCalibrationDecision::Complete);
  ASSERT_TRUE(tracker.has_terminal_result());

  // Proof 8: the exact offset the tracker handed back is what actually reaches
  // persistence - real ZOffsetConfigPersistence, real temp file, byte-checked.
  ASSERT_NEAR(complete_outcome.offset, terminal.offset, 1e-12);
  auto dir = make_tmpdir();
  std::string cfg = dir + "/printer.cfg";
  std::string bak = dir + "/printer.cfg.bak";
  {
    std::ofstream f(cfg, std::ios::binary | std::ios::trunc);
    f << "[bltouch]\n"
         "#*# <---------------------- SAVE_CONFIG ---------------------->\n"
         "#*# [bltouch]\n"
         "#*# z_offset = -0.200\n";
  }
  ZOffsetConfigPersistence persistence(cfg, bak);
  ASSERT_TRUE(persistence.patch_z_offset(complete_outcome.offset));

  std::ifstream check(cfg, std::ios::binary);
  std::ostringstream oss;
  oss << check.rdbuf();
  std::string written = oss.str();
  char expected[64];
  std::snprintf(expected, sizeof(expected), "#*# z_offset = %.3f", complete_outcome.offset);
  ASSERT_TRUE(written.find(expected) != std::string::npos);
}

TEST(IntegrationHarness, failure_full_replay_reaches_failed_and_never_touches_persistence) {
  auto fixture = load_fixture(kFailurePath);
  auto &steps = fixture.at("steps");

  auto before = parse_z_compensate_status(steps.at(0).at("status"));
  ASSERT_TRUE(before.well_formed);

  ZCompensateStatusTracker tracker;
  tracker.begin(before.id);

  auto mid_probe = parse_z_compensate_status(steps.at(1).at("status"));
  ASSERT_EQ(mid_probe.state, std::string("running"));
  auto busy_outcome = tracker.on_status(mid_probe);
  ASSERT_TRUE(busy_outcome.decision == ZCalibrationDecision::Busy);

  auto terminal = parse_z_compensate_status(steps.at(2).at("status"));
  ASSERT_TRUE(terminal.well_formed);
  ASSERT_EQ(terminal.state, std::string("error"));
  ASSERT_TRUE(terminal.has_error);
  auto failed_outcome = tracker.on_status(terminal);
  ASSERT_TRUE(failed_outcome.decision == ZCalibrationDecision::Failed);
  ASSERT_EQ(failed_outcome.error, terminal.error);
  ASSERT_TRUE(tracker.has_terminal_result());

  // A Failed decision must never reach patch_z_offset() - sensor_refine_failed() only ever
  // calls restore_backup(). Prove the persistence file is untouched by simply never calling
  // patch_z_offset() on this path and confirming the config still has its original content.
  auto dir = make_tmpdir();
  std::string cfg = dir + "/printer.cfg";
  std::string bak = dir + "/printer.cfg.bak";
  std::string original =
      "[bltouch]\n"
      "#*# <---------------------- SAVE_CONFIG ---------------------->\n"
      "#*# [bltouch]\n"
      "#*# z_offset = -0.200\n";
  {
    std::ofstream f(cfg, std::ios::binary | std::ios::trunc);
    f << original;
  }
  ZOffsetConfigPersistence persistence(cfg, bak);
  ASSERT_TRUE(persistence.backup());
  ASSERT_TRUE(persistence.restore_backup());  // exactly what sensor_refine_failed() does

  std::ifstream check(cfg, std::ios::binary);
  std::ostringstream oss;
  oss << check.rdbuf();
  ASSERT_EQ(oss.str(), original);
}

int main() {
  return minitest::run_all("integration_harness") > 0 ? 1 : 0;
}
